export const LOGGER_ACTIONS = {
	CATCH_FUNCTION: 'CATCH_FUNCTION',
	GEN_TOKEN: 'GEN_TOKEN',
	REGISTER: 'REGISTER'
}

export const LOGGER_TRANSACTIONS = {
	RUN_TRANSACTION_COMMIT: 'RUN_TRANSACTION_COMMIT',
	RUN_TRANSACTION_ROLLBACK: 'RUN_TRANSACTION_ROLLBACK'
}

export const LOGGER_ORDERS = {}
